help/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import *


urlpatterns = [
    path("help-home", help_home, name="help-home"),
    path("list-help", HelpListView.as_view(), name="list-help"),
    path("contact/", AddContactView.as_view(), name="contact"),
    path("recherche_help", search_help, name="search_help"),
    path("support", support, name="support"),
    path("maintenance-preventive", maintenance, name="maintenance"),
    path('it-software', itsoftware, name="itsoftware"),
    path('mise-jour-securite', mjs, name="mjs"),
    path('formations', formations, name="formations"),
    path('maintenance-corrective', maint_corrective, name="maint_corrective"),
    path("detail-help/<int:pk>", HelpDetailView.as_view(), name="detail-help"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mooc/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", home, name="home"),
    path("choix", choix, name="choix"),
    path("home-login", home_login, name="home-login"),
    path('detail_cours/<int:pk>', CoursDetailView.as_view(), name='detail-cours'),
    path('detail_formation/<int:pk>', FormationDetailView.as_view(), name='detail-formation'),
    path('cours_list', CoursListView.as_view(), name='cours_list'),
    path('all_cours', AllCoursListView.as_view(), name='all_cours'),
    path('detail_video/<int:pk>', TutorielDetailView.as_view(), name='detail-video'),
    path('register', AddUser.as_view(), name='register'),
    path('login', login_user, name='login'),
    path('logout', logout_user, name='logout'),
    path('suivre/add/<int:pk>', addSuivre, name='add_suivre'),
    path('list_suivres/<int:pk>', SuivreListView.as_view(), name='list_suivres'),
    path('quiz-view/<int:pk>/', QuizDetailView.as_view(), name='quiz-view'),
    path('quiz-view/<int:pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('quiz-view/<int:pk>/save', save_quiz_view, name='save-view'),
    path('suivre/delete/<int:pk>', deletesuivre, name='delete-suivre'),
    path('recherche', search, name='search'),
    path('profil/<int:pk>', ProfilDetailView.as_view(), name='profil'),
    path('cours_suivis/', CoursSuivisView.as_view(), name='cours_suivis'),
    path('delete_cours_suivis/delete/<int:pk>', deleteCoursSuivis, name='delete_cours_suivis'),
    path('reglage', reglageCompte, name='reglage-compte'),
    path('contact_login', AddContactView.as_view(), name='contact-login'),
    path('nos_formations', FormationListView.as_view(), name='formation'),
    path('contact_index', AddContactIndexView.as_view(), name='contact_index'),
    path('user/results/', UserResultsView.as_view(), name='user_results'),
    path('forum/<int:pk>', ForumDetailView.as_view(), name='forum'),
]

mymooc/mooc/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", home, name="home"),
    path("choix", choix, name="choix"),
    path("home-login", home_login, name="home-login"),
    path('detail_cours/<int:pk>', CoursDetailView.as_view(), name='detail-cours'),
    path('cours_list', CoursListView.as_view(), name='cours_list'),
    path('detail_video/<int:pk>', TutorielDetailView.as_view(), name='detail-video'),
    path('register', AddUser.as_view(), name='register'),
    path('login', login_user, name='login'),
    path('logout', logout_user, name='logout'),
    path('suivre/add/<int:pk>', addSuivre, name='add_suivre'),
    path('list_suivres/<int:pk>', SuivreListView.as_view(), name='list_suivres'),
    path('quiz-view/<int:pk>/', QuizlDetailView.as_view(), name='quiz-view'),
    path('quiz-view/<int:pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('quiz-view/<int:pk>/save', save_quiz_view, name='save-view'),
    path('suivre/delete/<int:pk>', deletesuivre, name='delete-suivre'),
    path('recherche', search, name='search'),
    path('profil/<int:pk>', ProfilDetailView.as_view(), name='profil'),
    path('cours_suivis/<int:pk>', CoursSuivisView.as_view(), name='cours_suivis'),
    path('delete_cours_suivis/delete/<int:pk>', deleteCoursSuivis, name='delete_cours_suivis'),
    path('reglage', reglageCompte, name='reglage-compte'),
    path('contact', contact_login, name='contact-login'),
    path('nos_formations', formation, name='formation'),
]

mymooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mooc.urls")),
    path('', include("help.urls")),
    path('my-admin/', include("app_admin.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mooc/models.py
from django.contrib.auth.models import User
from django.db import models
import random


# class Answers(models.Model):
#     question_id = models.IntegerField()
#     answer = models.CharField(max_length=200)
#
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.answer

# class QuizTaker(models.Model):
#     utilisateur = models.CharField(max_length=200)
#     pourcentage = models.CharField(max_length=200)
#     type = models.CharField(max_length=100)
#
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.pourcentage

#---------------------------------------------------------------------------------------------------------------------------------
class Postulant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    # GENRE = [('F', 'Feminin'), ('M', 'Masculin'), ]
    # NIVEAU = [('Dr', 'Doctorat'), ('M', 'Master'), ('L', 'Licence'),
    #           ('BTS', 'BTS'), ('BAC', 'BAC'), ]

    nom = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    # pays = models.CharField(max_length=200)
    # ville = models.CharField(max_length=200)
    # genre = models.CharField(max_length=1, choices=GENRE, )
    # date_naiss = models.DateField(blank=True, null=True)
    # niveau = models.CharField(max_length=5, choices=NIVEAU)
    confirm_pwd = models.CharField(max_length=200)
    # etablissement = models.CharField(max_length=200)
    # profession = models.CharField(max_length=200)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nom


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    comfirm_pwd = models.CharField(max_length=100)


class Formation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    nom_formation = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    img = models.ImageField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nom_formation


class Cours(models.Model):
    user_cours = models.ForeignKey(User, related_name='user_cours', on_delete=models.CASCADE, null=True, blank=True)
    formation = models.ForeignKey(Formation, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ManyToManyField(User, through='Suivre')
    nom_cours = models.CharField(max_length=200)
    description_cours = models.CharField(max_length=200)
    full_description = models.TextField()
    # module = models.CharField(max_length=100)
    image = models.ImageField()
    date_fin = models.DateField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nom_cours


class Tutoriel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    cours = models.ForeignKey(Cours, related_name="tutoriel", on_delete=models.CASCADE, null=True, blank=True)
    video = models.FileField()
    description = models.CharField(max_length=200)
    durer = models.CharField(max_length=20)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def is_liked_by_user(self, user):
        return self.tutoriellike_set.filter(user=user).exists()

    def likes_count(self):
        return self.tutoriellike_set.count()

    def __str__(self):
        return f"{self.video} / {self.description}"


# -------------------------------------------------------------------------------------------------------------------------------------------

class TutorielLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tutoriel = models.ForeignKey(Tutoriel, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'tutoriel')

    def __str__(self):
        return f"{self.user.username} / {self.tutoriel.description}"


# ------------------------------------------------------------------------------------------------------------------------

class Suivre(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} / {self.cours.nom_cours}"


# ---------------------------------------------------------------------------------------------------------------------------------------
class Quiz(models.Model):
    DIFF_CHOICES = {
        ('facile', 'Facile'),
        ('moyen', 'Moyen'),
        ('difficile', 'Difficile'),
    }
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    topic = models.CharField(max_length=200)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="durer du quiz en minutes")
    required_score_to_pass = models.IntegerField(help_text="required score en %")
    difficulity = models.CharField(max_length=9, choices=DIFF_CHOICES)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} / {self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizes'


# ---------------------------------------------------------------------------------------------------------------------------
class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answer_set.all()


# -------------------------------------------------------------------------------------------------------------------------------------------------
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"


# ---------------------------------------------------------------------------------------------------------------------------------
class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} / {self.score}"


# ---------------------------------------------------------------------------------------------------------------------------------------
class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    objet = models.CharField(max_length=200)
    message = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} / {self.message}"

mooc/forms.py
from django import forms
from .models import *


class PostulantForm(forms.ModelForm):
    class Meta:
        model = Postulant
        fields = ['nom', 'email', 'confirm_pwd']
        labels = {'nom': 'Nom complet', 'confirm_pwd': 'Confirmation de mot de passe'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nom'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['confirm_pwd'].widget.attrs.update({'class': 'form-control'})


# -------------------------------------------------------------------------------------------------------------------
class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['last_name', 'first_name', 'email', 'username', 'password']
        labels = {'last_name': 'Nom ', 'first_name': 'Prenom', 'email': 'Email', 'username': 'Nom utilisateur',
                  'password': 'Mot de passe'}
        widgets = {
            'password': forms.PasswordInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'type': 'password'})


# -------------------------------------------------------------------------------------------------------------------
class LoginForm(forms.Form):
    username = forms.CharField(label="Nom utilisateur", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={'class': 'form-control'}))


# -------------------------------------------------------------------------------------------------------------------

class UserForm(forms.Form):
    last_name = forms.CharField(label="Nom de famille", widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(label="Prénom", widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(label="Email", widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(label="Nom utilisateur", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="Nouveau Mot de passe",
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    pwd_confirm = forms.CharField(label="Mot de passe de confirmation",
                                  widget=forms.PasswordInput(attrs={'class': 'form-control'}))


# ----------------------------------------------------------------------------------------------------------------------
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'objet', 'message']
        labels = {'name': 'Nom ', 'email': 'Email', 'objet': 'Objet', 'message': 'Message'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['objet'].widget.attrs.update({'class': 'form-control'})
        self.fields['message'].widget.attrs.update({'class': 'form-control'})

mymooc/mooc/templates/choix.html
 {% extends "choix/base-choix.html" %}

 {% load static %}

 {% block content %}

<!-- ##### Blog Area Start ##### -->
<section class="blog-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-heading">
                    <h3>Bienvenue {{ user.username }} sur notre site vous avez le choix entre :</h3>
                </div>
            </div>
        </div>

        <div class="row">
            <!-- Single Blog Area -->
            <div class="col-12 col-md-6">
                <div class="single-blog-area mb-100 wow fadeInUp" data-wow-delay="250ms">
                    <a href="{% url 'list-help' %}"><img src="static/img/blog-img/2.jpg" alt=""></a>
                    <!-- Blog Content -->
                    <div class="blog-content">
                        <a href="#" class="blog-headline">
                            <h2>Services d'assistance</h2>
                        </a>
                        <div class="meta d-flex align-items-center">
                            <a href="#">Sarah Parker</a>
                            <span><i class="fa fa-circle" aria-hidden="true"></i></span>
                            <a href="#">Art &amp; Design</a>
                        </div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce enim nulla, mollis eu metus in, sagittis</p>
                    </div>
                </div>
            </div>

            <!-- Single Blog Area -->
            <div class="col-12 col-md-6">
                <div class="single-blog-area mb-100 wow fadeInUp" data-wow-delay="500ms">
                    <a href="{% url 'list_suivres' user.id %}"><img src="static/img/blog-img/1.jpg" alt=""></a>
                    <!-- Blog Content -->
                    <div class="blog-content">
                        <a href="#" class="blog-headline">
                            <h2>Video Learning</h2>
                        </a>
                        <div class="meta d-flex align-items-center">
                            <a href="#">Sarah Parker</a>
                            <span><i class="fa fa-circle" aria-hidden="true"></i></span>
                            <a href="#">Art &amp; Design</a>
                        </div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce enim nulla, mollis eu metus in, sagittis</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ##### Blog Area End ##### -->

{% endblock %}

mymooc/mooc/templates/cours_suivis.html
{% extends 'base-login.html' %}

{% load static %}

{% block content %}

    <!-- ##### Breadcumb Area Start ##### -->
    <div class="breadcumb-area" xmlns="http://www.w3.org/1999/html">
        <!-- Breadcumb -->
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home-login' %}">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'cours_list' %}">Nos Cours</a></li>
                {#            <li class="breadcrumb-item active" aria-current="page">Art &amp; Design</li>#}
            </ol>
        </nav>
    </div>
    <!-- ##### Breadcumb Area End ##### -->

    <style>

        .cercle {
            position: relative;
            width: 100px;
            height: 100px;
            border-radius: 50%;
            background-color: blue;
            color: white;
            text-align: center;
            line-height: 100px;
            font-size: 40px;
            margin-top: 30px;
        }

        .cercle::before {
            content: "{{ user.first_name|slice:':1' }}{{ user.last_name|slice:':1' }}";
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }

    </style>


    <section class="popular-courses-area section-padding-0-100">
        <div class="container">
            <div class="row">
                <div class="col-lg-12" style="display: flex; align-items: center;">
                    <div class="cercle" style="flex-shrink: 0;">
                        {{ user.first_name|slice:":1" }}{{ user.last_name|slice:":1" }}
                    </div>
                    {% if user.is_authenticated %}
                        <div style="margin-left: 20px; margin-top: 30px">
                            <p style="font-size: 20px">Bonjour,</p>
                            <h3 style="margin-top: 0px">{{ user.first_name }} {{ user.last_name }}</h3>
                        </div>
                    {% endif %}
                </div>
            </div>
            <hr class="my-4">


            <div class="row mt-5">
                <div class="col-lg-2 border-right">

                    <div class="mb-15">
                        <a href="{% url 'list_suivres' pk=user.id %}">
                            <button class="btn" style="background-color: blue; color: white">
                                <i class="fa fa-dashboard"> Tableau de bord</i>
                            </button>
                        </a>
                    </div>
                    <di>
                        <ul>
                            <ol><a href="{% url 'profil' user.id %}"><h5><i class="fa fa-user"> Mon Profil</i></h5></a>
                            </ol>
                            <ol><a href="{% url 'cours_suivis' user.id %}"><h5><i class="fa fa-book"> Cours Suivis</i></h5></a></ol>
                        </ul>
                    </di>

                    <hr>

                    <di>
                        <ul>
                            <ol><a href="{% url 'reglage-compte' %}"><h5><i class="fa fa-cog"> Réglage Compte</i></h5></a>
                            </ol>
                            <ol><a href="{% url 'logout' %}"><h5><i class="fa fa-sign-out"> Déconnexion</i></h5></a></ol>
                        </ul>
                    </di>

                </div>

                <div class="col-lg-10">
                    <!-- ##### Cool Facts Area Start ##### -->
                    <section class="cool-facts-area ">
                        <div class="container">

                            <div class="">
                                {% if object_list %}
                                    <div class="row">

                                        <div class="col-lg-8 ">
                                            <h4>Mes cours suivis</h4>
                                            {% for cours in cours_suivis %}
                                                <br>
                                                <div class="course-sidebar">
                                                    <!-- Widget -->
                                                    <div class="sidebar-widget">


                                                        <!-- Single Courses -->
                                                        <div class="single--courses d-flex align-items-center">
                                                            <div class="thumb">
                                                                <a href="{% url 'detail-cours' cours.id %}"><img
                                                                        src="{{ cours.image.url }}"
                                                                        alt="" style="height: 60px; width: 300px"></a>
                                                            </div>
                                                            <div class="content">
                                                                <a href="{% url 'detail-cours' cours.id %}">
                                                                    <h5>{{ cours.nom_cours }}</h5>
                                                                </a>
                                                                <a href="{% url 'delete_cours_suivis' cours.id %}"><i
                                                                        class="fa fa-trash"></i></a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>

                                    </div>
                                {% else %}
                                    <div class="col-lg-12 ">
                                        <p>On dirait que vous ne vous êtes encore inscrit à aucun cours</p>

                                        <a href="{% url 'cours_list' %}">
                                            <button class="btn  mb-30 w-50">Voir les cours</button>
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                    </section>
                    <!-- ##### Cool Facts Area End ##### -->


                </div>
                </di>

            </div>
        </div>

    </section>



{% endblock content %}

mymooc/mooc/templates/register.html
{% extends "base.html" %}

{% load static %}

{% block content %}

    </style>
    <div class="container">
        <div class="col-12 col-lg-12">
            <div class="contact-form mt-5">
                <h4>Inscription</h4>

                <div class="form-container" style="overflow: hidden;">
                    <form action="" method="POST" novalidate="novalidate">
                        {% csrf_token %}
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-danger text-center" role="alert">
                                    <strong>{{ message }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endfor %}
                        {% endif %}

                        <div class="form-group">
                            <label for="id_nom">Nom</label>
                            {{ form.last_name }}

                        </div>

                        <div class="form-group">
                            <label for="id_nom">Prénom</label>
                            {{ form.first_name }}

                        </div>
                        <div class="form-group">
                            <label for="id_email">Email</label>
                            {{ form.email }}

                        </div>
                        <div class="form-group">
                            <label for="id_username">Nom utilisateur</label>
                            {{ form.username }}
                            {% if form.username.errors %}
                                {% for error in form.username.errors %}

                                    <div class="div-error-{{ form.username.name }}"><small
                                            class="text-danger">{{ error }}</small></div>

                                {% endfor %}
                            {% endif %}

                        </div>
                        <div class="form-group">
                            <label for="id_password">Mot de passe</label>
                            <div class="password-wrapper" style="display: flex;">
                                {{ form.password }}
                                <button type="button" class="toggle-password" title="Afficher le mot de passe"
                                        style="max-height: 40px"><i class="fa fa-eye"></i></button>
                            </div>
                            {% if form.password.errors %}
                                {% for error in form.password.errors %}

                                    <div class="div-error-{{ form.password.name }}"><small
                                            class="text-danger">{{ error }}</small></div>

                                {% endfor %}
                            {% endif %}

                        </div>
                        {#                        <div class="form-group">#}
                        {#                            <label for="id_confirm_pwd">Confirmation de mot de passe</label>#}
                        {#                            <div class="password-wrapper" style="display: flex;">#}
                        {#                                <input class="form-control" type="password" name="confirm_pwd" id="id_confirm_pwd">#}
                        {#                                <button type="button" class="toggle-password" title="Afficher le mot de passe"#}
                        {#                                        style="max-height: 40px"><i class="fa fa-eye"></i></button>#}
                        {#                            </div>#}
                        {#                            {% for error in form.confirm_pwd.errors %}#}
                        {#                                <span class="text-danger">{{ error }}</span>#}
                        {#                            {% endfor %}#}
                        {#                        </div>#}
                        <button class="btn clever-btn w-100 mb-15" type="submit">Enregistrer</button>
                        <div class="text-center">
                            <h7>Avez-vous déjà un compte?</h7>
                            <button class="btn w-100"><a href="{% url 'login' %}">Se connecter</a>
                            </button>
                        </div>
                    </form>


                </div>


            </div>
        </div>
    </div>


    <script>
        const togglePasswordButtons = document.querySelectorAll('.toggle-password');
        togglePasswordButtons.forEach(button => {
            button.addEventListener('click', () => {
                const passwordField = button.previousElementSibling;
                const type = passwordField.getAttribute('type') === 'password' ? 'text' : 'password';
                passwordField.setAttribute('type', type);
                button.innerHTML = `<i class="fa ${type === 'password' ? 'fa-eye' : 'fa-eye-slash'}"></i>`;
                button.setAttribute('title', `${type === 'password' ? 'Afficher' : 'Cacher'} le mot de passe`);
            });
        });
    </script>


{% endblock %}