help/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import *


urlpatterns = [
    path("help-home", help_home, name="help-home"),
    path("list-help", HelpListView.as_view(), name="list-help"),
    path("contact/", AddContactView.as_view(), name="contact"),
    path("recherche_help", search_help, name="search_help"),
    path("support", support, name="support"),
    path("maintenance-preventive", maintenance, name="maintenance"),
    path('it-software', itsoftware, name="itsoftware"),
    path('mise-jour-securite', mjs, name="mjs"),
    path('formations', formations, name="formations"),
    path('maintenance-corrective', maint_corrective, name="maint_corrective"),
    path("detail-help/<int:pk>", HelpDetailView.as_view(), name="detail-help"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mymooc/help/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import *

urlpatterns = [
    path("help-home", help_home, name="help-home"),
    path("list-help", HelpListView.as_view(), name="list-help"),
    path("contact/", contact, name="contact"),
    path("recherche_help", search_help, name="search_help"),
    # path("files/<int:pk>/", FileDetailView.as_view(), name="files"),
    # path("helping/<int:pk>/", HelpingDetailView.as_view(), name="helping"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mymooc/mymooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mooc.urls")),
    path('', include("help.urls")),
    path('my-admin/', include("app_admin.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mymooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mooc.urls")),
    path('', include("help.urls")),
    path('my-admin/', include("app_admin.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

help/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Helping(models.Model):
    nom_helping = models.CharField(max_length=200)
    desc_helping = models.TextField()
    image = models.ImageField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nom_helping


# -------------------------------------------------------------------------------------------

class Files(models.Model):
    helping = models.ForeignKey(Helping, related_name="files", on_delete=models.CASCADE, null=True, blank=True)
    file = models.FileField()
    description = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.file} / {self.description}"


# ---------------------------------------------------------------------------------------------------------------------
class ContactHelp(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    objet = models.CharField(max_length=200)
    message = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} / {self.message}"

mooc/models.py
from django.contrib.auth.models import User
from django.db import models
import random


# class Answers(models.Model):
#     question_id = models.IntegerField()
#     answer = models.CharField(max_length=200)
#
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.answer

# class QuizTaker(models.Model):
#     utilisateur = models.CharField(max_length=200)
#     pourcentage = models.CharField(max_length=200)
#     type = models.CharField(max_length=100)
#
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.pourcentage

#---------------------------------------------------------------------------------------------------------------------------------
class Postulant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    # GENRE = [('F', 'Feminin'), ('M', 'Masculin'), ]
    # NIVEAU = [('Dr', 'Doctorat'), ('M', 'Master'), ('L', 'Licence'),
    #           ('BTS', 'BTS'), ('BAC', 'BAC'), ]

    nom = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    # pays = models.CharField(max_length=200)
    # ville = models.CharField(max_length=200)
    # genre = models.CharField(max_length=1, choices=GENRE, )
    # date_naiss = models.DateField(blank=True, null=True)
    # niveau = models.CharField(max_length=5, choices=NIVEAU)
    confirm_pwd = models.CharField(max_length=200)
    # etablissement = models.CharField(max_length=200)
    # profession = models.CharField(max_length=200)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nom


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    comfirm_pwd = models.CharField(max_length=100)


class Formation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    nom_formation = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    img = models.ImageField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nom_formation


class Cours(models.Model):
    user_cours = models.ForeignKey(User, related_name='user_cours', on_delete=models.CASCADE, null=True, blank=True)
    formation = models.ForeignKey(Formation, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ManyToManyField(User, through='Suivre')
    nom_cours = models.CharField(max_length=200)
    description_cours = models.CharField(max_length=200)
    full_description = models.TextField()
    # module = models.CharField(max_length=100)
    image = models.ImageField()
    date_fin = models.DateField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nom_cours


class Tutoriel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    cours = models.ForeignKey(Cours, related_name="tutoriel", on_delete=models.CASCADE, null=True, blank=True)
    video = models.FileField()
    description = models.CharField(max_length=200)
    durer = models.CharField(max_length=20)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def is_liked_by_user(self, user):
        return self.tutoriellike_set.filter(user=user).exists()

    def likes_count(self):
        return self.tutoriellike_set.count()

    def __str__(self):
        return f"{self.video} / {self.description}"


# -------------------------------------------------------------------------------------------------------------------------------------------

class TutorielLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tutoriel = models.ForeignKey(Tutoriel, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'tutoriel')

    def __str__(self):
        return f"{self.user.username} / {self.tutoriel.description}"


# ------------------------------------------------------------------------------------------------------------------------

class Suivre(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} / {self.cours.nom_cours}"


# ---------------------------------------------------------------------------------------------------------------------------------------
class Quiz(models.Model):
    DIFF_CHOICES = {
        ('facile', 'Facile'),
        ('moyen', 'Moyen'),
        ('difficile', 'Difficile'),
    }
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    topic = models.CharField(max_length=200)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="durer du quiz en minutes")
    required_score_to_pass = models.IntegerField(help_text="required score en %")
    difficulity = models.CharField(max_length=9, choices=DIFF_CHOICES)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} / {self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizes'


# ---------------------------------------------------------------------------------------------------------------------------
class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answer_set.all()


# -------------------------------------------------------------------------------------------------------------------------------------------------
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"


# ---------------------------------------------------------------------------------------------------------------------------------
class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} / {self.score}"


# ---------------------------------------------------------------------------------------------------------------------------------------
class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    objet = models.CharField(max_length=200)
    message = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} / {self.message}"

mymooc/help/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Helping(models.Model):
    nom_helping = models.CharField(max_length=200)
    desc_helping = models.CharField(max_length=200)
    image = models.ImageField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nom_helping


# -------------------------------------------------------------------------------------------

class Files(models.Model):
    helping = models.ForeignKey(Helping, related_name="files", on_delete=models.CASCADE, null=True, blank=True)
    file = models.FileField()
    description = models.CharField(max_length=200)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.file} / {self.description}"

help/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView
from django.db.models import Prefetch
from moviepy.video.io.VideoFileClip import VideoFileClip

from mooc.forms import ContactForm
from mooc.models import Formation, Cours, Contact
from .form import ContactHelpForm
from .models import *


# Create your views here.

def help_home(request):
    help = Helping.objects.all().order_by('-created_at')
    format = Formation.objects.all().order_by('-created_at')
    cours = Cours.objects.all().order_by('-created_at')
    return render(request, "indexhelp-login.html", {"formations": format, "cours": cours, "helps": help})


# ---------------------------------------------------------------------------------------------------------
class AddContactView(LoginRequiredMixin, CreateView):
    model = ContactHelp
    form_class = ContactHelpForm
    template_name = "contact.html"
    success_url = reverse_lazy("contact")

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Le message a été envoyé avec succès.")
        return response


# -------------------------------------------------------------------------------------------------------------------------------
def support(request):
    return render(request, "support.html")


# ---------------------------------------------------------------------------------------------------------------------------
def maintenance(request):
    return render(request, "maintenance.html")


# --------------------------------------------------------------------------------------------------------------------------------------
def itsoftware(request):
    return render(request, "itsoftware.html")


# ----------------------------------------------------------------------------------------------------------------------------------------------
def mjs(request):
    return render(request, "mjs.html")


# --------------------------------------------------------------------------------------------------------------------------------------
def formations(request):
    return render(request, "formations.html")


# --------------------------------------------------------------------------------------------------------------------------------------
def maint_corrective(request):
    return render(request, "maint_corrective.html")


# --------------------------------------------------------------------------------------------------------------------------------------
class HelpListView(LoginRequiredMixin, ListView):
    model = Helping
    template_name = "help.html"
    paginate_by = 20  # if pagination is desired

    def get_queryset(self):
        return Helping.objects.order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


# ---------------------------------------------------------------------------------------------------------

def search_help(request):
    query = request.GET["search"]
    list_help = Helping.objects.filter(nom_helping__icontains=query)
    return render(request, 'search_help.html', {"list_help": list_help})


# ---------------------------------------------------------------------------------------------------------
class HelpDetailView(LoginRequiredMixin, DetailView):
    model = Helping
    template_name = "detail-help.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        video_file = context['object'].files.first().file.path
        video_clip = VideoFileClip(video_file)
        duration = int(video_clip.duration)
        minutes, seconds = divmod(duration, 60)
        context['duration'] = '{:02d}:{:02d}'.format(minutes, seconds)

        # Ajouter la liste de Helping au contexte
        context['helping_list'] = Helping.objects.all().order_by('-created_at')

        return context

help/templates/__navhelp-login.html
{% load static %}

<style>

    .cercle1 {
        position: relative;
        width: 50px;
        height: 50px;
        border-radius: 50%;
        background-color: blue;
        color: white;
        text-align: center;
        line-height: 50px;
        font-size: 30px;
        margin-top: 0px;
    }


</style>
<header class="fixed-top header">
    <!-- top header -->
    <div class="top-header py-2 bg-white">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-lg-4 text-center text-lg-left">
            <a class="text-color mr-3" href="callto:+443003030266"><strong>CALL</strong> +228 93 56 73 37</a>
            <ul class="list-inline d-inline">
              <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-facebook"></i></a></li>
              <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-twitter-alt"></i></a></li>
              <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-linkedin"></i></a></li>
              <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-instagram"></i></a></li>
            </ul>
          </div>
          <div class="col-lg-8 text-center text-lg-right">
            <ul class="list-inline">
              {% comment %} <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="notice.html">notice</a></li>
              <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="research.html">research</a></li>
              <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="scholarship.html">SCHOLARSHIP</a></li> 
              <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="{% url 'login' %}" data-toggle="modal" data-target="#loginModal">Se connecter</a></li>{% endcomment %}
              <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="{% url 'logout' %}">Déconnexion</a></li>
              {% if user.is_authenticated %}
              <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block"><i class="ti-user" style="color: orange"></i><span style="color: orange"> {{ user.username }}</span></a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- navbar -->
    <div class="navigation w-100">
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light p-0">
          <a class="navbar-brand" href="{% url 'help-home' %}"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
          <button class="navbar-toggler rounded-0" type="button" data-toggle="collapse" data-target="#navigation"
            aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
  
          <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav ml-auto text-center">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'help-home' %}">Home</a>
              </li>
              <li class="nav-item @@about">
                <a class="nav-link" href="{% url 'list-help' %}">Nos Services Assistances</a>
              </li>
              {% comment %} <li class="nav-item @@courses">
                <a class="nav-link" href="{% url 'cours_list' %}">Nos Cours</a>
              </li>
              <li class="nav-item @@events">
                <a class="nav-link" href="{% url 'formation' %}">Nos formations</a>
              </li> {% endcomment %}
              <li class="nav-item @@blog">
                <a class="nav-link" href="{% url 'contact' %}">Contact</a>
              </li>
              
             {% comment %} <li class="nav-item dropdown view">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                  Pages
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="teacher.html">Teacher</a>
                  <a class="dropdown-item" href="teacher-single.html">Teacher Single</a>
                  <a class="dropdown-item" href="notice.html">Notice</a>
                  <a class="dropdown-item" href="notice-single.html">Notice Details</a>
                  <a class="dropdown-item" href="research.html">Research</a>
                  <a class="dropdown-item" href="scholarship.html">Scholarship</a>
                  <a class="dropdown-item" href="course-single.html">Course Details</a>
                  <a class="dropdown-item" href="event-single.html">Event Details</a>
                  <a class="dropdown-item" href="blog-single.html">Blog Details</a>
                </div>
              </li>
              <li class="nav-item @@contact">
                <a class="nav-link" href="contact.html">CONTACT</a>
              </li> {% endcomment %}
            </ul>
          </div>
        </nav>
      </div>
    </div>
  </header>
  <!-- /header -->
  <!-- Modal -->
  {% comment %} <div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content rounded-0 border-0 p-4">
              <div class="modal-header border-0">
                  <h3>Créer un compte</h3>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="modal-body">
                  <div class="login">
                    {% csrf_token %}
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-danger text-center" role="alert">
                                        <strong>{{ message }}</strong>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                {% endfor %}
                            {% endif %}

                      <form action="{% url 'register' %}" class="row" method="POST" novalidate>
                        {% csrf_token %}
                          <div class="col-12">
                              <input type="text" class="form-control mb-3" id="signupPhone" name="last_name" placeholder="Nom">
                          </div>
                          <div class="col-12">
                              <input type="text" class="form-control mb-3" id="signupName" name="first_name" placeholder="Prénom">
                          </div>
                          <div class="col-12">
                            <input type="text" class="form-control mb-3" id="signupName" name="email" placeholder="Email">
                        </div>
                          <div class="col-12">
                              <input type="email" class="form-control mb-3" id="signupEmail" name="username" placeholder="Nom utilisateur">
                              {% if form.username.errors %}
                                    {% for error in form.username.errors %}

                                        <div class="div-error-{{ form.username.name }}"><small
                                                class="text-danger">{{ error }}</small></div>

                                    {% endfor %}
                                {% endif %}
                          </div>
                          <div class="col-12">
                              <input type="password" class="form-control mb-3" id="signupPassword" name="password" placeholder="Mot de passe">
                              {% if form.password.errors %}
                                    {% for error in form.password.errors %}

                                        <div class="div-error-{{ form.password.name }}"><small
                                                class="text-danger">{{ error }}</small></div>

                                    {% endfor %}
                                {% endif %}
                          </div>
                          <div class="col-12">
                              <button type="submit" class="btn btn-primary">SIGN UP</button>
                          </div>
                      </form>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content rounded-0 border-0 p-4">
              <div class="modal-header border-0">
                  <h3>Connexion</h3>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="modal-body">
                {% if messages %}
                        {% for message in messages %}
                            {% if message.tags == 'success' %}
                                <div class="alert alert-success text-center"><strong>{{ message }}</strong></div>
                            {% elif message.tags == 'error' %}
                                <div class="alert alert-danger text-center"><strong>{{ message }}</strong></div>
                            {% endif %}
                        {% endfor %}
                {% endif %}
                
                  <form action="{% url 'login' %}" class="row" method="POST" novalidate>
                    {% csrf_token %}
                      <div class="col-12">
                          <input type="text" class="form-control mb-3" id="loginPhone" name="loginPhone" placeholder="Phone">
                      </div> 
                      <div class="col-12">
                        {% if form.username.errors %}
                        {% for error in form.username.errors %}
                            <div class="div-error-{{ form.username.name }}"><small
                                    class="text-danger">{{ error }}</small></div>
                        {% endfor %}
                       {% endif %}
                          <input type="text" class="form-control mb-3" id="loginName" name="username" placeholder="Nom utilisateur">
                      </div>
                      <div class="col-12">
                        {% if form.password.errors %}
                                    {% for error in form.password.errors %}
                                        <div class="div-error-{{ form.password.name }}"><small
                                                class="text-danger">{{ error }}</small></div>
                                    {% endfor %}
                                {% endif %}
                          <input type="password" class="form-control mb-3" id="loginPassword" name="password" placeholder="Mot de passe">
                      </div>
                      <div class="col-12">
                          <button type="submit" class="btn btn-primary">SE CONNECTER</button>
                          <p class="mt-2">Vous n'avez pas de compte ? <a href="{% url 'register' %}" data-toggle="modal" data-target="#signupModal">Créer le
                            compte</a></p>
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div> {% endcomment %}
  

help/templates/files.html
{% extends "help/basehelp-login.html" %}

{% load static %}

{% block content %}
    <style>
        .page-title-section.overlay {
            border-bottom-right-radius: 10% 30%;
            overflow: hidden;
        }

        .page-title-section.overlay::before {
            border-bottom-right-radius: 10% 30%;
            overflow: hidden;
        }

        .success-video {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            z-index: 1;
            width: 0%;
            max-width: 500px;
            height: 0%;
            max-height: 500px;


        }

        .event-title {
            margin-top: -10px;
        }

        .single-upcoming-events .date-fee .events-fee a {
            border-radius: 0 0 0 0;
        }
    </style>

    <!-- page title -->
    <section class="page-title-section overlay" data-background="{% static 'images/backgrounds/page-title.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <ul class="list-inline custom-breadcrumb">
                        <li class="list-inline-item"><a class="h2 text-primary font-secondary" href="courses.html">Nos
                            cours</a></li>
                        <li class="list-inline-item text-white h3 font-secondary "></li>
                    </ul>
                    <p class="text-lighten">Nos cours offrent un bon compromis entre l'évolution continue privilégiée
                        par certaines formations
                        et l'accent mis sur d'autres domaines d'études.</p>
                </div>
            </div>
        </div>
    </section>
    <!-- /page title -->

    <!-- courses -->




{% endblock %}